import Button from '../components/Button'
import { about } from '../content'

// Page images live in public/files/cv-pages, generated by scripts/render-cv.sh.
// Re-run `npm run render:cv` after replacing the PDF and update this count.
const CV_PAGES = 6

export default function CV() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <header className="mb-10">
        <span className="text-xs font-bold uppercase tracking-widest text-green mb-2 block">
          Curriculum Vitae
        </span>
        <h1 className="text-3xl md:text-4xl font-extrabold text-ink mb-3">CV</h1>
        <p className="text-lg text-muted">Download or view my full curriculum vitae.</p>
      </header>

      <div className="bg-panel border border-line rounded-lg p-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
        <div>
          <h2 className="text-ink font-bold text-lg mb-1">Ignacio Urbina</h2>
          <p className="text-muted text-sm">
            Ph.D. Candidate in Political Science, Stony Brook University
          </p>
        </div>
        <Button href={about.profile.cvUrl} variant="primary" size="lg">
          Download CV (PDF)
        </Button>
      </div>

      {/*
        Desktop browsers render the PDF itself. Mobile browsers have no inline
        PDF plugin, so they fall through to the <object>'s child content — the
        page images below, rather than an apology.
      */}
      <div className="mt-10">
        <object
          data={about.profile.cvUrl}
          type="application/pdf"
          className="hidden md:block w-full border border-line rounded-lg bg-panel"
          style={{ height: 'calc(100vh - 20rem)' }}
        >
          <CvPages />
        </object>
        <div className="md:hidden">
          <CvPages />
        </div>
      </div>
    </div>
  )
}

function CvPages() {
  return (
    <div className="space-y-4">
      {Array.from({ length: CV_PAGES }, (_, i) => (
        <img
          key={i}
          src={`/files/cv-pages/cv-${i + 1}.webp`}
          alt={`Curriculum vitae, page ${i + 1} of ${CV_PAGES}`}
          width={1000}
          height={1414}
          /* always lazy: whichever branch is hidden at this breakpoint then
             fetches nothing, so desktop never downloads the page images */
          loading="lazy"
          decoding="async"
          className="w-full h-auto border border-line rounded-lg bg-white shadow-sm"
        />
      ))}
      <p className="text-muted-light text-xs text-center pt-2">
        Page images of the CV. Use Download for the searchable PDF.
      </p>
    </div>
  )
}
